#!/bin/bash

source "${BASH_SOURCE%/*}/../common"

force_stop dock-mysql

root_pw="mysqlpw"

run --detach \
    --env MYSQL_ROOT_PASSWORD=$root_pw \
    --env MYSQL_DATABASE=hys \
    --env MYSQL_DATABASE1=switcher \
    --env MYSQL_DATABASE2=exchange \
    --env MYSQL_DATABASE3=matrix \
    --publish 13306:3306 \
    --name dock-mysql \
    crazycode/mysql

echo "Root password:  $root_pw"
echo
echo "Database:       $db"
echo "User:           $user"
echo "User password:  $user_pw"
